#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Descargas/wall.jpg &
pgrep -xf "polybar left" > /dev/null || polybar left &
pgrep -xf "polybar center" > /dev/null || polybar center &
pgrep -xf "polybar right" > /dev/null || polybar right &
pgrep -x urxvtd > /dev/null || urxvtd &

bspc monitor -d 1 2 3 4

bspc config border_width         0
bspc config window_gap           8

bspc config top_padding		40
bspc config left_padding	 8
bspc config right_padding	 8
bspc config bottom_padding	 8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a URxvt desktop='^1' follow=on
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a Firefox-esr desktop='^3' follow=on
